name: Build and deploy IDE web app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Setup JVM and Clojure tooling
      - name: 'Setup OpenJDK'
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 21

      - name: Setup Clojure build tools
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.0.1488

      - name: Setup cache for Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          # key: cljdeps-${{ hashFiles('project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-

      - name: Setup proto and bun 
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Install npm dependencies
        run: bun install

      - name: Setup SWI-Prolog
        uses: smucclaw/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: '9.3.16-3-gc9b66bc73-nobleppa2'

      - name: Install SWI-Prolog dependencies
        run: bun install:swipl-deps

      - name: Precompile SWI-Prolog files to qlf
        run: bun build:swipl-public-qlf

      - name: Build IDE web app
        run: bun build:ide

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload app artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

  deploy:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4