name: Build JVM lib uberjar

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Setup JVM and Clojure tooling
      - name: 'Setup OpenJDK'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25

      - name: Setup Clojure build tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: 1.12.2.1565
          bb: 1.12.208

      - name: Setup cache for Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          # key: cljdeps-${{ hashFiles('project.clj') }}
          # key: cljdeps-${{ hashFiles('build.boot') }}
          restore-keys: cljdeps-

      - name: Setup proto and bun 
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Setup SWI-Prolog
        uses: smucclaw/setup-swi-prolog@master
        with:
          swi-prolog-branch: devel
          swi-prolog-version: '9.3.31-1-g17f51b5b3-nobleppa2'

      - name: Install SWI-Prolog dependencies
        run: bun install:swipl-deps

      - name: Precompile SWI-Prolog files to qlf
        run: bun build:swipl-public-qlf

      - name: Build JVM lib uberjar
        run: bb uber-github-workflow-ubuntu